### ISSUE TITLE
user agreement state not updated

### ISSUE THREAD

**Issue by Rineee** [liqd/adhocracy-plus#2284]
**URL:** 
**user:** 
**expected behaviour:** when I add a comment and agree to terms of use, I dont have to agree again when I add a reply to another comment on the same page
**behaviour:** the state is not updated (or passed) and I have to tick the box again when adding a reply to another comment
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by lthueer** [comment]
@Rineee for me this is working. Maybe it has beed fixed with the quick release done by @fuzzylogic2000 regarding this issue: https://github.com/liqd/adhocracy-plus/issues/2276?

**Comment by Rineee** [comment]
@lthueer For me this is still not working. What did you test exactly?

**Comment by lthueer** [comment]
@Rineee you're right! It's only updating the user agreement when the page is reloaded
